---
abstract: 'Subclass Vroom::Vroom to make clickable links'
author:
  - 'Dr Bean <drbean at (a) cpan dot (.) org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101310'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Vroom-Vroom-Link
recommends: {}
requires:
  IO::All: 0
  Template::Toolkit::Simple: 0
  Vroom::Vroom: 0
  parent: 0
version: 0.01
